name: Auto build workflow

on:
  push:
    branches: [ main ]
    paths:
      - '**.yml'
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-on-windows:
    name: Build on Windows
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-2019
    steps:
    - name: Run build script
      id: build-script
      run: |
        git clone --depth 1 --branch v1.2.2 https://github.com/catboost/catboost.git
        cd catboost

        set VSCMD_DEBUG=2

        "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

        # --msvc_toolset 14.28.29333
        python build/build_native.py --build-root-dir=./build_no_cuda --targets catboost --msvs_version 2022
